Time = 't'
Temperature = 'T'
CelsiusTemperature = '\theta'
Force = 'F'
Width = 'w'
Height = 'h'
Length = 'l'
CrossSection = 'A'
ContactArea = 'A_\mathrm{c}'
FlowStress = 'k_\mathrm{f}'
DeformationResistance = 'k_\mathrm{Wm}'
CoulombFrictionFactor = '\mu'
StictionFactor = 'm'
NormalStress = '\sigma'
ShearStress = '\tau'
Strain = '\varepsilon'
LogStrain = '\varphi'
Draught = '\gamma'
Spread = '\beta'
Elongation = '\lambda'
Radius = 'r'
Diameter = 'd'
FreibergFlowStressBaseFactor = 'A'
FreibergFlowStressCoefficient = 'm'
Equivalent = '{#1}_\mathrm{eq}'
Change = '\Delta #1'
X = 'x'
Y = 'y'
Z = 'z'
HeatTransferFactor = '\alpha'
BoltzmannCoefficient = '\epsilon_0'
RelativeRadiationCoefficient = '\epsilon_\mathrm{r}'
Expectation = '\mu'
StandardDeviation = '\sigma'
GammaDistributionAlpha = '\alpha'
GammaDistributionBeta = '\beta'
Estimated = '\hat{#1}'
InterpassDuration = 't_\mathrm{P}'
MinInterpassDuration = 't_\mathrm{P0}'
RollGap = 's'
Velocity = 'v'
RollRadius = 'R_\mathrm{W}'
In = '#1_0'
Density = '\varrho'
ThermalCapacity = 'c_\mathrm{p}'