Abs = '\lvert #1 \rvert'
BoltzmannCoefficient = '\epsilon_0'
CelsiusTemperature = '\vartheta'
Change = '\Delta #1'
ContactArea = 'A_\mathrm{c}'
Correlation = 'r'
CoulombFrictionFactor = '\mu'
CrossSection = 'A'
DeformationResistance = 'k_\mathrm{Wm}'
Density = '\varrho'
Diameter = 'd'
Draught = '\gamma'
E = '\mathrm{e}'
Elongation = '\lambda'
Equivalent = '{#1}_\mathrm{eq}'
Estimated = '\hat{#1}'
Expectation = '\mu'
FillingRatio = 'i'
FlowStress = 'k_\mathrm{f}'
FlowStressA = 'A'
FlowStressM = 'm_#1'
Force = 'F'
FreibergFlowStressBaseFactor = 'A'
FreibergFlowStressCoefficient = 'm'
GammaDistributionAlpha = '\alpha'
GammaDistributionBeta = '\beta'
HeatTransferFactor = '\alpha'
Height = 'h'
In = '#1_0'
InterpassDuration = 't_\mathrm{P}'
Length = 'l'
LogStrain = '\varphi'
LogStrainRate = '\dot{\varphi}'
Mean = '\mu'
MinInterpassDuration = 't_\mathrm{P0}'
MinPauseDuration = 't_0'
NormalStress = '\sigma'
PauseDuration = 't'
Radius = 'r'
RelativeRadiationCoefficient = '\epsilon_\mathrm{r}'
RelativeStandardDeviationDepression = '\Delta\bar{\sigma}'
RollForce = 'F_\mathrm{W}'
RollGap = 's'
RollRadius = 'R_\mathrm{W}'
RollTorque = 'M_\mathrm{W}'
ShearStress = '\tau'
Spread = '\beta'
StandardDeviation = '\sigma'
StictionFactor = 'm'
Strain = '\varepsilon'
StrainRate = '\dot{\varepsilon}'
Temperature = 'T'
ThermalCapacity = 'c_\mathrm{p}'
Time = 't'
Variance = '\sigma^2'
Velocity = 'v'
Width = 'w'
X = 'x'
Y = 'y'
Z = 'z'