Abs = '\lvert #1 \rvert'
ActivationEnergy = 'Q'
Area = 'A'
CelsiusTemperature = '\vartheta'
Change = '\Delta #1'
Contact = '#1_\mathrm{Contact}'
Convection = '#1_\mathrm{Convection}'
Correlation = 'r'
CoulombFrictionFactor = '\mu'
Critical = '\mathrm{cr}'
CrossSection = 'A'
Deformation = '\LogStrain'
DeformationResistance = 'k_\mathrm{Wm}'
Density = '\varrho'
Diameter = 'd'
Draught = '\gamma'
Duration = '\Delta\mspace{-1mu}t'
E = '\mathrm{e}'
Elongation = '\lambda'
Environment = '#1_\infty'
Equivalent = '{#1}_\mathrm{eq}'
Estimated = '\hat{#1}'
Expectation = '\mu'
FillingRatio = 'i'
FlowStress = 'k_\mathrm{f}'
FlowStressA = 'A'
FlowStressM = 'm_#1'
Force = 'F'
FreibergFlowStressBaseFactor = 'A'
FreibergFlowStressCoefficient = 'm'
GammaDistributionAlpha = '\alpha'
GammaDistributionBeta = '\beta'
GasConstant = 'R'
GrainSize = 'd'
HeatTransferFactor = '\alpha'
Height = 'h'
In = '\mathrm{in}'
Length = 'l'
LogStrain = '\varphi'
LogStrainRate = '\dot{\varphi}'
Max = '#1_\mathrm{max}'
Mean = '\mu'
Min = '#1_\mathrm{min}'
NormalStress = '\sigma'
Out = '\mathrm{out}'
Pause = '#1_\mathrm{P}'
Radiation = '#1_\mathrm{Radiation}'
Radius = 'r'
RecrystallizedFraction = 'X'
Reference = '\mathrm{ref}'
RelativeRadiationCoefficient = '\epsilon_\mathrm{r}'
RelativeStandardDeviationDepression = '\Delta\bar{\sigma}'
Roll = '#1_\mathrm{R}'
RollForce = 'F_\mathrm{W}'
RollGap = 's'
RollRadius = 'R_\mathrm{W}'
RollTorque = 'M_\mathrm{W}'
ShearStress = '\tau'
Spread = '\beta'
StandardDeviation = '\sigma'
StefanBoltzmannCoefficient = '\epsilon_0'
StictionFactor = 'm'
Strain = '\varepsilon'
StrainRate = '\dot{\varepsilon}'
Surface = '#1_\mathrm{S}'
Temperature = 'T'
ThermalCapacity = 'c_\mathrm{p}'
Time = 't'
Variance = '\sigma^2'
Velocity = 'v'
Volume = 'V'
WeibullDistributionScale = '\beta'
WeibullDistributionShape = '\alpha'
Width = 'w'
X = 'x'
Y = 'y'
Z = 'z'