[build]
packages = [
    "weiner_variation",
]

[envs.default]
path = ".venv"

[envs.sim]
path = ".venv_sim"
dependencies = [
    "pandas",
    "coconut",
    "jupyter",
    "jupyterlab",
    "jupytext",
    "tqdm",
    "pyroll-basic ~= 2.0",
    "pyroll-elastic-mill-spring ~= 2.0",
    "pyroll-jmak-recrystallization ~= 2.0",
    "papermill ~= 2.3.0",
]
