[build]
packages = [
    "weiner_variation",
]

[envs.default]
path = ".venv"

[envs.sim_base]
dependencies = [
    "pandas",
    "coconut",
    "jupyter",
    "jupyterlab",
    "jupytext",
    "tqdm",
    "pyroll-basic ~= 2.0",
]

[envs.sim_base.scripts]
jupyter = "coconut --jupyter lab"

[envs.sim_elastic]
template = "sim_base"
path = ".venv_sim_elastic"
extra-dependencies = [
    "pyroll-elastic-mill-spring ~= 2.0",
]

