"""Initializes the project directory by generating some configuration files based on the current system."""

from pathlib import Path

ROOT_DIR = Path(__file__).parent
NOTICE = "generated by initialize.py - DO NOT MODIFY!"


def generate_dotenv():
    """Generate a .env file for setting environment while running with pipenv."""
    dotenv_content = f"""# {NOTICE}
    PYTHONPATH="{ROOT_DIR}:"
    """

    (ROOT_DIR / ".env").write_text(dotenv_content)


if __name__ == "__main__":
    generate_dotenv()
